export const HANDLE_CHANGE = 'HANDLE_CHANGE';
export const HANDLE_EDIT = 'HANDLE_EDIT';
export const GET_TODOS_FROM_DB = 'GET_TODOS_FROM_DB';
export const MAIN_DRAWER_OPEN = 'MAIN_DRAWER_OPEN';
export const MAIN_DRAWER_CLOSE = 'MAIN_DRAWER_CLOSE';
export const ACTION_EDIT_DRAWER = 'EDIT_DRAWER';
